### PR TITLE
Support official amazon file format

### PR DESCRIPTION
**Pull request by mikesherov**
Thanks so so much for this wonderful tool.

Just thought I'd be a good OSS citizen and pass this patch along. If you accept the PR, please cut a release so I don't have to rely on my fork.

### CODE REVIEW

**Comment by andrewrk** [comment]
Looks good, I'll merge and cut a release later

**Comment by mikesherov** [comment]
Oops, ignore the last two commits on this PR.

**Comment by mikesherov** [comment]
Yeah, only the first commit applies. Sorry about that!

**Comment by mikesherov** [comment]
superceded by #33 Sorry for the confusion!

**Pull request closed without merging**
