### PR TITLE
Support offical AWS environment variables

### PR DESCRIPTION
**Pull request by gmathieu**
`AWS_ACCESS_KEY_ID`  and `AWS_SECRET_ACCESS_KEY`

Kept old variables undocumented for backwards compatibility.

http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#credentials

### CODE REVIEW

**Comment by skolsuper** [comment]
Why'd you close this @gmathieu?

**Comment by gmathieu** [comment]
It was sitting there for months. I figured no one was interested in it. Happy to restore the branch.

**Comment by skolsuper** [comment]
I know the feeling, but it doesn't hurt to leave it open if there is not some other problem with it, the maintainer may get around to it eventually.

**Comment by ferminromero** [comment]
This is unexpected behavior.

**Comment by af6140** [comment]
I found this feature is useful

**Comment by th0th** [comment]
Will this ever be merged? Or isn't this project maintained anymore :(

**Pull request closed without merging**
